[build-system]
# setuptools !=60.9.1, !=60.9.2, !=60.9.3 for bug missing no-local-version
requires = ["setuptools>=42,!=60.9.1,!=60.9.2,!=60.9.3", "wheel", "setuptools_scm[toml]>=4.1.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"

[tool.black]
line-length = 120
